### ISSUE TITLE
Issue with Loading Web App while implementing Continuous Deployment

### ISSUE THREAD

**Issue by PraveenAnil** [Microsoft/MCW-OSS-PaaS-and-DevOps#1]
In **_Exercise 5 -> Task 9 ->  Step 10_**  , the web page shows “Not Found” with the image build done via CD Pipeline. The release log in VSTS is showing as successful.

If I use the private image tagged as latest ( which was built locally in the VM and pushed to ACR ) it is working fine.
I was able to complete the rest of the exercises using the locally pushed image in ACR.

**Comment by kylebunting** [comment]
@PraveenAnil, I ran into the same issue when testing, and was not able to get VSTS to successfully deploy via the CD pipeline. I have updated to lab to use Jenkins for the entire CI/CD pipeline, and use Docker and the Azure App Service Jenkins plugin to deploy directly into the Web App for Containers instance.
