### ISSUE TITLE
Adding "Contributing" section

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#10]
In the [Readme file](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/2018-august-testfix/README.md) let's add a section before "References" outline the how people can contribute with a link.

> Contributing
> If you'd like to contribute to this sample, see CONTRIBUTING.MD.
> 
> This project has adopted the Microsoft Open Source Code of Conduct. For more information, see the Code of Conduct FAQ or contact opencode@microsoft.com with any additional questions or comments.
> 
>

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Contributing link is located on the main MCW page.
