### ISSUE TITLE
Task 2: Create a Linux virtual machine

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#11]
In [Task 2: Create a Linux virtual machine](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/2018-august-testfix/Hands-on%20lab/Appendix-A.md#task-2-create-a-linux-virtual-machine) let's update the following:

- Remove the step to add inbound role to the VM (step 8)
- Use the new bade screenshoot where it allows you to add RDP port directly 
![image](https://user-images.githubusercontent.com/5002831/44954240-ec31da00-aeaf-11e8-956a-5242918e2719.png)

**Comment by kylebunting** [comment]
@hkamel, This has been addressed in the March 2019 Update.
