### ISSUE TITLE
Task 5: Launch the starter application

### ISSUE THREAD

**Issue by ShivaniThadiyan** [Microsoft/MCW-OSS-PaaS-and-DevOps#12]
In task 5>Step 3 > I ran the command **npm install** but not able to install it. you can see the give error: https://cloudbeesstg.blob.core.windows.net/ossdevopserror/Screenshot_1.png

**Comment by hkamel** [comment]
Hello @ShivaniThadiyan you need to change the directory to the cloned application, the screenshot showing that you still in the context of the workshop directory and not the starter app.

please check [Task 4](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-4-clone-the-starter-application)

> Now, change the directory to the cloned project by entering the following at the prompt:

**Comment by hkamel** [comment]
Hello @ShivaniThadiyan I assume this solved you problem.

**Comment by waltermyersiii** [comment]
Hosam, do we need to update the documentation?

**Comment by hkamel** [comment]
@waltermyersiii we have an open enhacement #4 about moving the starter app to the workshop folder instead.
