### ISSUE TITLE
November test/fix QC

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-OSS-PaaS-and-DevOps#15]
Hi Jay,
QC for the November test/fix is complete, thank you!  I've merged your PR, deleted the Nov test/fix branch and updated the HTML links.  Can you please take a look at the open issues #11 #9 #8 #7 #6 for me?  I think some may have been resolved with your test/fix and can be closed.  If they need to wait for a full update, please label them either Improvement or Enhancement (whichever applies).  I'm working on #10 so nothing for you to do there.

**Comment by jstulo** [comment]
Hi Dawnmarie

I closed a couple of the issues as resolved or otherwise labeled and commented on them.

**Comment by DawnmarieDesJardins** [comment]
You're awesome, thank you!
