### ISSUE TITLE
March 2019 - Scheduled content update 

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-OSS-PaaS-and-DevOps#16]
@joelhulen @kylebunting
Solliance team -
This workshop is scheduled for an update in March. We will be combining this workshop with the OSS DevOps workshop. Please update this issue with suggested content changes. Once done, we'll assign to our SME team for review and additional feedback.

**Comment by kylebunting** [comment]
Here are my suggested updates for this MCW:

- Merge OSS DevOps into this MCW
- Update VM provisioning to add RDP port directly (issue #11).
- Use Azure CLI to create a Service Principal for Jenkins (issue #9).
- Update steps for creation of Cosmos DB collection (issue #7).
- Move start app into repo (issue #4).
- Update starter app packages to latest versions to remove security vulnerabilities in solution.

**Comment by waltermyersiii** [comment]
Looks good. With MERN, we should stick with this as the primary and merge OSS DevOps in. Bring over the migration of VMs from a hosted environment into this one. They are already very close so should only be one workshop.

**Comment by dmckinstry** [comment]
Unfortunately, I only had time to skim.  Nothing jumped out at me but I definitely agree with both @kylebunting and @waltermyersiii.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hi Kyle,
Please move forward on this update with comments above.
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Updated Development Timeline
Suggested updates due: 3/5/19 (complete)
SME review: 3/6/19 – 3/7/19 (complete)
Draft due: 4/8/19
SME review: 4/9/19 – 4/18/19
Final due: 4/22/19
Publish: 4/24/19

**Comment by kylebunting** [comment]
Final updates are complete. This is ready for QC and merge.
