### ISSUE TITLE
Use of ARM Templates vs. Azure Portal

### ISSUE THREAD

**Issue by snpdev** [Microsoft/MCW-OSS-PaaS-and-DevOps#18]
For the [March 2019 - Scheduled content update](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/issues/16), has thought been given to the use of ARM Templates for resource provisioning, as opposed to Azure Portal? This is in reference to:

- [Provision Cosmos DB using the MongoDB API](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-1-provision-cosmos-db-using-the-mongodb-api)
- [Create an Azure Container Registry](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-1-create-an-azure-container-registry)
- [Provision Web App for Containers](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-1-provision-web-app-for-containers)
- [Provision a Function App](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-1-provision-a-function-app)

In the DevOps spirit, I think we should encourage infrastructure as code as much as possible.

Given the depth of this workshop, as a facilitator I not would expect people to build the ARM Templates, but at least review them and update parameters. For a workshop featuring ARM Template programming, I would turn to [Continuous delivery in Azure DevOps](https://github.com/Microsoft/MCW-Continuous-Delivery-in-Azure-DevOps).

**Comment by kylebunting** [comment]
@snpdev, for the latest update, I kept things as they were. My reason is that the target audience for this is OSS developers, and they may not be totally familiar with the Azure portal, so I think it is good to have them work in that environment a bit to get used to how to provision resources in there. ARM templates and infrastructure as code would fit well, so I don't disagree with your request, but think it might be best to keep that for another lab. Just having them review ARM templates can be confusing if they are not familiar with them.
