### ISSUE TITLE
Exercise 7 Task 1: Twilio, Address Required 

### ISSUE THREAD

**Issue by snpdev** [Microsoft/MCW-OSS-PaaS-and-DevOps#20]
After step 11 of Exercise 7 Task 1, "Select **Choose this Number**", there is an **Address Required** step prior to step 12 "Select **Done** on the Congratulations dialog."

I entered an address, but it would not move me to a next step in the phone number selection workflow. The impression I have is that I would need to buy a phone number.

Given this issue, and that lab users may _not_ be OK with opening a Twilio account (IMHO), perhaps this service should be replaced with something less intrusive?

**Comment by DawnmarieDesJardins** [comment]
@kylebunting
Thanks Mike! This workshop is currently undergoing an update. Assigning this issue to author for review.

**Comment by kylebunting** [comment]
@snpdev, In the latest update, I removed the use of Twilio, and set it up to send emails via a free SendGrid account in place of that. It is less intrusive, and much faster to configure.
