### ISSUE TITLE
Exercise 6: Unable to deploy Function app in Hands-on-lab-RG

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-OSS-PaaS-and-DevOps#22]
1. In [Exercise 4](https://github.com/microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#exercise-4-set-up-web-app-for-containers) : We need to provision **Web app for Containers with Linux OS** in RG **hands-on-lab-RG**.
2. In [Exercise 6](https://github.com/microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#exercise-6-create-azure-function-for-order-processing) we need to provision a **Function App with Windows OS** in same RG **hands-on-lab-RG** , but we are unable to provision Function app due to below mentioned error:

"The requested service plan can not be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one."

![image](https://user-images.githubusercontent.com/48020356/60196760-83ab5380-985b-11e9-860f-34ce353bf706.png)

3. When we are deploying Web App for Containers In the lab guide its mentioned to select the default App Service Plan SKU, but in the RBAC/Policy we need provide specify the SKU. Can you please update the instructions for creating a App Service plan mentioning the specific SKU such as **B1**.

Can you please check fix this **ASAP**.

Thanks,
Amal Gireesh

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hi Kyle - please review and advise.
Thanks, Dawnmarie

**Comment by kylebunting** [comment]
I'll look into this and get a fix in place.

**Comment by amalgireesh** [comment]
Any updation?

**Comment by kylebunting** [comment]
@amalgireesh, I just checked in a fix for this. The new steps will be to create the function app in a new resource group.

**Comment by amalgireesh** [comment]
Thank you @kylebunting
