### ISSUE TITLE
Exercise 3 Task 4 not able to fetch image in docker explorer

### ISSUE THREAD

**Issue by himanshu311996** [microsoft/MCW-OSS-PaaS-and-DevOps#25]
In **exercise 3 task 4** having issue to fetch image in docker explorer. I tried multiple times but the facing same issue every-time.
![error 3](https://user-images.githubusercontent.com/17895399/65439087-40558680-de44-11e9-8b6c-5e683b6cb80f.png)

**Comment by timahenning** [comment]
Hi Amit,

We will try to review your issue as soon as possible.  Next time, please allow for 5 - 10 business days for support issues.  https://microsoftcloudworkshop.com/.  Let me see what I can do.

Tim

**Comment by akn9050** [comment]
Hi Tim,

Looks like it was a temporary issue, it worked today.


Thanks,
Amit Kumar

**Comment by timahenning** [comment]
Thanks for the update.

**Comment by crpietschmann** [comment]
@akn9050 I just ran through Exercise 3 Task 4 of the hands-on lab and everything worked as expected. Did all the other Docker commands, like `docker images` run successfully in previous steps?

**Comment by kylebunting** [comment]
Amit,
I’ll take a look at this early tomorrow, so hopefully we can get a resolution before your lab on the 26th.

Regards,
Kyle

**Comment by kylebunting** [comment]
Nevermind. Looks like this has been closed…

Kyle
