### ISSUE TITLE
New LabVM Doesn't Get Proper Desktop Config

### ISSUE THREAD

**Issue by mfarley281** [microsoft/MCW-OSS-PaaS-and-DevOps#27]
I'm doing this lab now and wasn't able to RDP to my LabVM after using the ARM Template (the 1-click deployment from the lab doc) to deploy it.

I then SSH'd into the box to investigate. It appeared that parts of labvmconfig.sh ran/worked (e.g. all the packages were installed). However, there was no sign of the first two sections of labvmconfig.sh having run properly. There was no ~/.xsession file, no /etc/X11/Xwrapper.config, and lxde was *not* installed.

Running the first part of the labvmconfig.sh manually fixed everything:

```
export DEBIAN_FRONTEND=noninteractive
# Install LXDE lxde.org and xrdp - (make sure to open 3389 on the NSG of the azure vm)
apt-get update
apt-get install -y lxde
apt-get install -y xrdp
/etc/init.d/xrdp start

# Prepare XWindows System
sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
sudo touch ~/.xsession
echo "startlxde" > ~/.xsession

```
Everything beyond this part in the script was in-place already.

**Comment by kylebunting** [comment]
@mfarley281, I've run the ARM template twice now, and both times everything provisions as expected. Perhaps something went wrong during your particular instance run? 

Any chance you could try to run the ARM template again to validate it still doesn't work for you?

**Comment by mfarley281** [comment]
Just tried and got the same (incorrect) result. I'm defaulting to region southeastasia since I live in Manila, Philippines. Perhaps it's something with that region? Can you try on southeastasia?

**Comment by timahenning** [comment]
@mfarley281 Can you try the Central US region to see if you get the same result?

**Comment by mfarley281** [comment]
@timahenning I just tried both Central US and Southeast Asia again. And they both *worked*. I have no idea what's changed? Maybe something changed in the SE Asia region? Maybe it's a rare race condition?

**Comment by timahenning** [comment]
@mfarley281 I glad to hear everything worked.  If you have this issue again, please try the 'Central US' region to rule out regional problems.  We would have a comparison to work from at that point.
