### ISSUE TITLE
MongoDB doesn't autostart on LabVM

### ISSUE THREAD

**Issue by mfarley281** [microsoft/MCW-OSS-PaaS-and-DevOps#28]
At one point in the lab directions (after granting the user permissions to use docker), the lab instructs the user to "reboot" if in doubt. However, MongoDB does not automatically start on boot. So you must manually run "**sudo service mongod start**" before continuing with the lab (and again anytime you reboot). Ideally, the service should be autostarting.

**Comment by kylebunting** [comment]
@mfarley281, thanks for the recommendation. I agree this makes total sense to add to the setup for the lab VM. I will include this in the next round of updates I do for the workshop.

**Comment by kylebunting** [comment]
This enhancement was added by pull request #29. Closing issue.
