### ISSUE TITLE
Unable to Configure Continuous Integration with Jenkins

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-OSS-PaaS-and-DevOps#35]
In Exercise 5, Task 4, Unable to find the Github project option from the list where we build a new **free style project** . 
Enclosing the image for reference.

![7e1dda21-272d-4e16-8ee5-c35911dc6c2f](https://user-images.githubusercontent.com/52440474/79572708-09460b80-80db-11ea-970a-9c8e91c85155.jpg)

**Comment by DawnmarieDesJardins** [comment]
Closing as complete with merge of PR #36
