### ISSUE TITLE
mcw-oss-paas-devops starter app

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#4]
In [Task 5: Fork the starter app](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/Before%20the%20HOL.md#task-5-fork-the-starter-app) It will be better to centralize the lab content under one repo, can we move the starter app under Microsoft organization and better under the same lab in a different folder.

**Comment by waltermyersiii** [comment]
Hi Hosam,

We need to keep this all contained within a single repo. Is there a way we could better organize in this repo?

walter

**Comment by kylebunting** [comment]
All the starter project files have been moved into a lab-files folder under the Hands-on lab folder in this repo.
