### ISSUE TITLE
1.6.3. Task 3: Pre-create and scale collections- Step 4

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#6]
In [1.6.3. Task 3: Pre-create and scale collections
](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/2018-august-testfix/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#163-task-3-pre-create-and-scale-collections) do we need step 4? we are creating the collections from scratch in the newly created cosmos db with the right throughput.

**Comment by jstulo** [comment]
Step 4 is only needed in the case where the application ran and created these collections before they are created manually. "If the users and plans collections already exist from your application connecting, edit each collection to increase their throughput using the following steps:"
