### ISSUE TITLE
1.6.2. Task 2: Update database connection string- step 7

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#7]
Following the lab sequence, at this stage (step 6 and 7) we didn't create the collection database so the database name "best-for-you-organics" may confuse users to use the cosmosdb name instead.

I highly recommend:

- Either mention that this will be the collection database created later in this lab (Task 3)

- Or move step 6 and 7 under task 3 after step 14

**Comment by kylebunting** [comment]
Corrected in the March 2019 update.
