### ISSUE TITLE
1.8.1. Task 1: Provision Web App for Containers

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#8]
In [1.8.1. Task 1: Provision Web App for Containers](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/2018-august-testfix/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#181-task-1-provision-web-app-for-containers) move "OS: Select Linux" under web app configuration as it's not a container configuration. 
![image](https://user-images.githubusercontent.com/5002831/44925786-681d0c80-ad60-11e8-9aef-044f3caefcc9.png)

**Comment by jstulo** [comment]
Because the OS option is part of the Create UI, I am note sure why we would remove this from the instructions.
