### ISSUE TITLE
Task 6: Add an Azure service principal for Jenkins

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-OSS-PaaS-and-DevOps#9]
In [Task 6: Add an Azure service principal for Jenkins](https://github.com/Microsoft/MCW-OSS-PaaS-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20OSS%20PaaS%20and%20DevOps.md#task-6-add-an-azure-service-principal-for-jenkins) let's simplify the steps by using Azure CLI and `az ad sp create-fpr-rbac` [command](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac)

**Comment by kylebunting** [comment]
Addressed in the March 2019 update.
